[2023-01-27T03:08:49.603+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: hdfs_spark_dag.download_data manual__2023-01-27T02:08:26.168498+00:00 [queued]>
[2023-01-27T03:08:49.613+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: hdfs_spark_dag.download_data manual__2023-01-27T02:08:26.168498+00:00 [queued]>
[2023-01-27T03:08:49.613+0100] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T03:08:49.613+0100] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-27T03:08:49.613+0100] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T03:08:49.633+0100] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): download_data> on 2023-01-27 02:08:26.168498+00:00
[2023-01-27T03:08:49.635+0100] {standard_task_runner.py:55} INFO - Started process 11558 to run task
[2023-01-27T03:08:49.639+0100] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'hdfs_spark_dag', 'download_data', 'manual__2023-01-27T02:08:26.168498+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/hdfs_spark_dag.py', '--cfg-path', '/tmp/tmp0m85g1j0']
[2023-01-27T03:08:49.640+0100] {standard_task_runner.py:83} INFO - Job 166: Subtask download_data
[2023-01-27T03:08:49.685+0100] {task_command.py:388} INFO - Running <TaskInstance: hdfs_spark_dag.download_data manual__2023-01-27T02:08:26.168498+00:00 [running]> on host LAPTOP-J6R38EUB.localdomain
[2023-01-27T03:08:49.804+0100] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=hdfs_spark_dag
AIRFLOW_CTX_TASK_ID=download_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-27T02:08:26.168498+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-27T02:08:26.168498+00:00
[2023-01-27T03:08:49.805+0100] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-27T03:08:49.806+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        sudo docker exec -it docker-hadoop_namenode_1 sh -c "hadoop fs -get /output/output.txt /hadoop/data/output.txt"\n    ']
[2023-01-27T03:08:49.810+0100] {subprocess.py:86} INFO - Output:
[2023-01-27T03:08:51.390+0100] {subprocess.py:93} INFO - get: `/hadoop/data/output.txt': File exists
[2023-01-27T03:08:51.822+0100] {subprocess.py:97} INFO - Command exited with return code 1
[2023-01-27T03:08:51.831+0100] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-01-27T03:08:51.834+0100] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=hdfs_spark_dag, task_id=download_data, execution_date=20230127T020826, start_date=20230127T020849, end_date=20230127T020851
[2023-01-27T03:08:51.852+0100] {standard_task_runner.py:100} ERROR - Failed to execute job 166 for task download_data (Bash command failed. The command returned a non-zero exit code 1.; 11558)
[2023-01-27T03:08:51.860+0100] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-27T03:08:51.874+0100] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
