[2023-01-23T13:44:31.430+0100] {processor.py:153} INFO - Started process (PID=30342) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:44:31.431+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:44:31.432+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:44:31.432+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:44:31.436+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:44:31.435+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:44:31.437+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:44:31.462+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.035 seconds
[2023-01-23T13:44:48.621+0100] {processor.py:153} INFO - Started process (PID=30459) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:44:48.622+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:44:48.622+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:44:48.622+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:44:48.626+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:44:48.625+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:44:48.626+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:44:48.647+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.029 seconds
[2023-01-23T13:45:18.798+0100] {processor.py:153} INFO - Started process (PID=30588) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:45:18.800+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:45:18.800+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:45:18.800+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:45:18.804+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:45:18.803+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:45:18.804+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:45:18.831+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.036 seconds
[2023-01-23T13:45:49.170+0100] {processor.py:153} INFO - Started process (PID=30695) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:45:49.171+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:45:49.172+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:45:49.172+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:45:49.175+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:45:49.175+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:45:49.176+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:45:49.197+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.029 seconds
[2023-01-23T13:46:19.942+0100] {processor.py:153} INFO - Started process (PID=30821) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:46:19.944+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:46:19.945+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:46:19.945+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:46:19.948+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:46:19.948+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:46:19.949+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:46:19.967+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.028 seconds
[2023-01-23T13:46:50.261+0100] {processor.py:153} INFO - Started process (PID=30928) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:46:50.263+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:46:50.264+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:46:50.264+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:46:50.271+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:46:50.269+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:46:50.271+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:46:50.298+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.040 seconds
[2023-01-23T13:47:20.630+0100] {processor.py:153} INFO - Started process (PID=31031) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:47:20.631+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:47:20.632+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:47:20.631+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:47:20.635+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:47:20.634+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:47:20.635+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:47:20.654+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.028 seconds
[2023-01-23T13:47:51.000+0100] {processor.py:153} INFO - Started process (PID=31136) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:47:51.001+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:47:51.002+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:47:51.002+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:47:51.005+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:47:51.004+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:47:51.005+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:47:51.023+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.028 seconds
[2023-01-23T13:48:21.399+0100] {processor.py:153} INFO - Started process (PID=31239) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:48:21.400+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:48:21.401+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:48:21.401+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:48:21.405+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:48:21.404+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:48:21.405+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:48:21.429+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.033 seconds
[2023-01-23T13:48:51.706+0100] {processor.py:153} INFO - Started process (PID=31344) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:48:51.708+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:48:51.709+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:48:51.709+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:48:51.712+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:48:51.712+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:48:51.713+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:48:51.732+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.029 seconds
[2023-01-23T13:49:22.096+0100] {processor.py:153} INFO - Started process (PID=31450) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:49:22.097+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:49:22.097+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:49:22.097+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:49:22.101+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:49:22.100+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:49:22.102+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:49:22.124+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.031 seconds
[2023-01-23T13:49:52.472+0100] {processor.py:153} INFO - Started process (PID=31554) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:49:52.473+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:49:52.474+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:49:52.474+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:49:52.477+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:49:52.476+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:49:52.478+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:49:52.497+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.029 seconds
[2023-01-23T13:50:22.837+0100] {processor.py:153} INFO - Started process (PID=31659) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:50:22.838+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:50:22.838+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:50:22.838+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:50:22.841+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:50:22.840+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:50:22.841+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:50:22.860+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.026 seconds
[2023-01-23T13:50:53.197+0100] {processor.py:153} INFO - Started process (PID=31763) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:50:53.198+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:50:53.199+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:50:53.199+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:50:53.202+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:50:53.201+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:50:53.202+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:50:53.222+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.028 seconds
[2023-01-23T13:51:23.579+0100] {processor.py:153} INFO - Started process (PID=31870) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:51:23.580+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:51:23.580+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:51:23.580+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:51:23.584+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:51:23.583+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:51:23.584+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:51:23.603+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.027 seconds
[2023-01-23T13:51:53.947+0100] {processor.py:153} INFO - Started process (PID=31972) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:51:53.948+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:51:53.949+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:51:53.949+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:51:53.952+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:51:53.951+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:51:53.952+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:51:53.971+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.027 seconds
[2023-01-23T13:52:24.258+0100] {processor.py:153} INFO - Started process (PID=32077) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:52:24.260+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:52:24.261+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:52:24.260+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:52:24.263+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:52:24.263+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:52:24.263+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:52:24.281+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.025 seconds
[2023-01-23T13:52:54.632+0100] {processor.py:153} INFO - Started process (PID=1009) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:52:54.633+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:52:54.634+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:52:54.633+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:52:54.636+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:52:54.636+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:52:54.637+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:52:54.661+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.033 seconds
[2023-01-23T13:53:25.038+0100] {processor.py:153} INFO - Started process (PID=1539) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:53:25.040+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:53:25.040+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:53:25.040+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:53:25.043+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:53:25.043+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:53:25.043+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:53:25.068+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.033 seconds
[2023-01-23T13:53:55.415+0100] {processor.py:153} INFO - Started process (PID=1642) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:53:55.416+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:53:55.417+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:53:55.417+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:53:55.420+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:53:55.419+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:53:55.420+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:53:55.440+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.028 seconds
[2023-01-23T13:54:25.783+0100] {processor.py:153} INFO - Started process (PID=1748) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:54:25.784+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:54:25.785+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:54:25.784+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:54:25.788+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:54:25.787+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:54:25.788+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:54:25.808+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.028 seconds
[2023-01-23T13:54:56.150+0100] {processor.py:153} INFO - Started process (PID=1852) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:54:56.152+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:54:56.152+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:54:56.152+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:54:56.155+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:54:56.154+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:54:56.155+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:54:56.174+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.027 seconds
[2023-01-23T13:55:26.512+0100] {processor.py:153} INFO - Started process (PID=1958) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:55:26.512+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:55:26.513+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:55:26.513+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:55:26.516+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:55:26.516+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:55:26.517+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:55:26.535+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.026 seconds
[2023-01-23T13:55:56.857+0100] {processor.py:153} INFO - Started process (PID=2061) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:55:56.858+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:55:56.859+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:55:56.859+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:55:56.862+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:55:56.861+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:55:56.862+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:55:56.881+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.027 seconds
[2023-01-23T13:56:27.223+0100] {processor.py:153} INFO - Started process (PID=2166) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:56:27.225+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:56:27.225+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:56:27.225+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:56:27.228+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:56:27.228+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:56:27.229+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:56:27.249+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.028 seconds
[2023-01-23T13:56:57.589+0100] {processor.py:153} INFO - Started process (PID=2271) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:56:57.591+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:56:57.592+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:56:57.592+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:56:57.594+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:56:57.594+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:56:57.595+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:56:57.614+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.028 seconds
[2023-01-23T13:57:27.964+0100] {processor.py:153} INFO - Started process (PID=2376) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:57:27.966+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:57:27.967+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:57:27.967+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:57:27.970+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:57:27.970+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:57:27.971+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:57:27.990+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.029 seconds
[2023-01-23T13:57:58.327+0100] {processor.py:153} INFO - Started process (PID=2479) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:57:58.328+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:57:58.328+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:57:58.328+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:57:58.332+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:57:58.331+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:57:58.332+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:57:58.356+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.033 seconds
[2023-01-23T13:58:28.689+0100] {processor.py:153} INFO - Started process (PID=2585) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:58:28.690+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:58:28.691+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:58:28.691+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:58:28.694+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:58:28.694+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:58:28.695+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:58:28.715+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.029 seconds
[2023-01-23T13:58:59.150+0100] {processor.py:153} INFO - Started process (PID=2688) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:58:59.151+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:58:59.152+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:58:59.152+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:58:59.155+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:58:59.155+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:58:59.155+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:58:59.174+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.027 seconds
[2023-01-23T13:59:29.617+0100] {processor.py:153} INFO - Started process (PID=2794) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:59:29.618+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T13:59:29.618+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:59:29.618+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:59:29.622+0100] {logging_mixin.py:137} INFO - [2023-01-23T13:59:29.621+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T13:59:29.622+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T13:59:29.640+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.026 seconds
[2023-01-23T14:00:00.095+0100] {processor.py:153} INFO - Started process (PID=2897) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T14:00:00.096+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T14:00:00.097+0100] {logging_mixin.py:137} INFO - [2023-01-23T14:00:00.097+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T14:00:00.100+0100] {logging_mixin.py:137} INFO - [2023-01-23T14:00:00.099+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T14:00:00.100+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T14:00:00.124+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.032 seconds
[2023-01-23T14:00:30.574+0100] {processor.py:153} INFO - Started process (PID=3002) to work on /home/manu/airflow/dags/my_dag.py
[2023-01-23T14:00:30.576+0100] {processor.py:743} INFO - Processing file /home/manu/airflow/dags/my_dag.py for tasks to queue
[2023-01-23T14:00:30.576+0100] {logging_mixin.py:137} INFO - [2023-01-23T14:00:30.576+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/manu/airflow/dags/my_dag.py
[2023-01-23T14:00:30.579+0100] {logging_mixin.py:137} INFO - [2023-01-23T14:00:30.579+0100] {dagbag.py:343} ERROR - Failed to import: /home/manu/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/manu/airflow/dags/my_dag.py", line 2, in <module>
    from airflow.operators.hdfs_operator import HDFSOperator
ModuleNotFoundError: No module named 'airflow.operators.hdfs_operator'
[2023-01-23T14:00:30.580+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/manu/airflow/dags/my_dag.py
[2023-01-23T14:00:30.598+0100] {processor.py:175} INFO - Processing /home/manu/airflow/dags/my_dag.py took 0.026 seconds
